/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeineai/bindgen@0.2.1.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const NavEntry = IDL.Rec();
export const _ImmutableObjectStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _ImmutableObjectStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _ImmutableObjectStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const Error = IDL.Variant({
  'FrontendOriginsNotConfigured' : IDL.Null,
  'MixedSsoSources' : IDL.Record({
    'otherKeys' : IDL.Vec(IDL.Text),
    'ssoKeys' : IDL.Vec(IDL.Text),
  }),
  'Stale' : IDL.Record({ 'ageNs' : IDL.Nat }),
  'MalformedCandid' : IDL.Null,
  'AmbiguousAttribute' : IDL.Record({
    'field' : IDL.Text,
    'sources' : IDL.Vec(IDL.Text),
  }),
  'NoAttributes' : IDL.Null,
  'UnknownNonce' : IDL.Null,
  'UntrustedSsoSource' : IDL.Record({ 'domain' : IDL.Text }),
  'MissingField' : IDL.Text,
  'FrontendOriginMismatch' : IDL.Record({
    'got' : IDL.Text,
    'expected' : IDL.Vec(IDL.Text),
  }),
});
export const Result__1 = IDL.Variant({ 'ok' : IDL.Null, 'err' : Error });
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const CreateBlogPostInput = IDL.Record({
  'title' : IDL.Text,
  'content' : IDL.Text,
  'isPublished' : IDL.Bool,
  'slug' : IDL.Text,
  'author' : IDL.Text,
  'readTime' : IDL.Text,
  'coverImage' : ExternalBlob,
  'excerpt' : IDL.Text,
  'category' : IDL.Text,
});
export const BlogPostId = IDL.Nat;
export const Timestamp = IDL.Int;
export const BlogPost = IDL.Record({
  'id' : BlogPostId,
  'title' : IDL.Text,
  'content' : IDL.Text,
  'isPublished' : IDL.Bool,
  'createdAt' : Timestamp,
  'slug' : IDL.Text,
  'author' : IDL.Text,
  'readTime' : IDL.Text,
  'coverImage' : ExternalBlob,
  'excerpt' : IDL.Text,
  'category' : IDL.Text,
});
export const ShoppingItem = IDL.Record({
  'productName' : IDL.Text,
  'currency' : IDL.Text,
  'quantity' : IDL.Nat,
  'priceInCents' : IDL.Nat,
  'productDescription' : IDL.Text,
});
export const GalleryItemId = IDL.Nat;
export const GalleryItem = IDL.Record({
  'id' : GalleryItemId,
  'title' : IDL.Text,
  'createdAt' : Timestamp,
  'description' : IDL.Text,
  'category' : IDL.Text,
  'image' : ExternalBlob,
  'eventDate' : IDL.Opt(Timestamp),
});
export const Value = IDL.Variant({
  'int' : IDL.Int,
  'nat' : IDL.Nat,
  'float' : IDL.Float64,
  'bool' : IDL.Bool,
  'null' : IDL.Null,
  'text' : IDL.Text,
});
export const Cell = IDL.Record({ 'value' : Value, 'name' : IDL.Text });
export const Result = IDL.Record({
  'hasMore' : IDL.Bool,
  'rows' : IDL.Vec(IDL.Vec(Cell)),
});
export const HeroVideoSlot = IDL.Record({
  'key' : IDL.Text,
  'posterUrl' : IDL.Text,
  'videoUrl' : IDL.Text,
});
export const HeroVideoConfig = IDL.Record({ 'slots' : IDL.Vec(HeroVideoSlot) });
NavEntry.fill(
  IDL.Record({
    'href' : IDL.Text,
    'text' : IDL.Text,
    'children' : IDL.Vec(NavEntry),
  })
);
export const NavConfig = IDL.Record({ 'entries' : IDL.Vec(NavEntry) });
export const PostSitemapEntry = IDL.Record({
  'slug' : IDL.Text,
  'category' : IDL.Text,
  'lastmod' : Timestamp,
});
export const StripeSessionStatus = IDL.Variant({
  'completed' : IDL.Record({
    'userPrincipal' : IDL.Opt(IDL.Text),
    'response' : IDL.Text,
  }),
  'failed' : IDL.Record({ 'error' : IDL.Text }),
});
export const PublishedPostsPage = IDL.Record({
  'total' : IDL.Nat,
  'posts' : IDL.Vec(BlogPost),
});
export const StripeConfiguration = IDL.Record({
  'allowedCountries' : IDL.Vec(IDL.Text),
  'secretKey' : IDL.Text,
});
export const HttpHeader = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
export const HttpRequestResult = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(HttpHeader),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : HttpRequestResult,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(HttpHeader),
});
export const UpdateBlogPostInput = IDL.Record({
  'title' : IDL.Text,
  'content' : IDL.Text,
  'isPublished' : IDL.Bool,
  'slug' : IDL.Text,
  'author' : IDL.Text,
  'readTime' : IDL.Text,
  'coverImage' : ExternalBlob,
  'excerpt' : IDL.Text,
  'category' : IDL.Text,
});

export const idlService = IDL.Service({
  '_immutableObjectStorageBlobsAreLive' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [IDL.Vec(IDL.Bool)],
      ['query'],
    ),
  '_immutableObjectStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_immutableObjectStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_immutableObjectStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_ImmutableObjectStorageCreateCertificateResult],
      [],
    ),
  '_immutableObjectStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_ImmutableObjectStorageRefillInformation)],
      [_ImmutableObjectStorageRefillResult],
      [],
    ),
  '_immutableObjectStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initialize_access_control' : IDL.Func([], [], []),
  '_internet_identity_sign_in_finish' : IDL.Func([], [Result__1], []),
  '_internet_identity_sign_in_start' : IDL.Func([], [IDL.Vec(IDL.Nat8)], []),
  'addAdmin' : IDL.Func([IDL.Principal], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createBlogPost' : IDL.Func([CreateBlogPostInput], [BlogPost], []),
  'createCheckoutSession' : IDL.Func(
      [IDL.Vec(ShoppingItem), IDL.Text, IDL.Text],
      [IDL.Text],
      [],
    ),
  'createGalleryItem' : IDL.Func(
      [ExternalBlob, IDL.Text, IDL.Text, IDL.Opt(Timestamp), IDL.Text],
      [GalleryItem],
      [],
    ),
  'deleteBlogPost' : IDL.Func([BlogPostId], [IDL.Bool], []),
  'deleteGalleryItem' : IDL.Func([GalleryItemId], [IDL.Bool], []),
  'execute' : IDL.Func([IDL.Text], [Result], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getGalleryItems' : IDL.Func([], [IDL.Vec(GalleryItem)], ['query']),
  'getHeroVideoConfig' : IDL.Func([], [HeroVideoConfig], ['query']),
  'getNavConfig' : IDL.Func([], [NavConfig], ['query']),
  'getPostBySlug' : IDL.Func([IDL.Text], [IDL.Opt(BlogPost)], ['query']),
  'getPostSlugs' : IDL.Func([], [IDL.Vec(PostSitemapEntry)], ['query']),
  'getStripeSessionStatus' : IDL.Func([IDL.Text], [StripeSessionStatus], []),
  'isAdmin' : IDL.Func([IDL.Principal], [IDL.Bool], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isStripeConfigured' : IDL.Func([], [IDL.Bool], ['query']),
  'listAllPosts' : IDL.Func([], [IDL.Vec(BlogPost)], ['query']),
  'listPublishedPosts' : IDL.Func(
      [IDL.Nat, IDL.Nat],
      [PublishedPostsPage],
      ['query'],
    ),
  'listPublishedPostsByCategory' : IDL.Func(
      [IDL.Text, IDL.Nat, IDL.Nat],
      [PublishedPostsPage],
      ['query'],
    ),
  'schema' : IDL.Func([], [IDL.Text], ['query']),
  'setHeroVideoConfig' : IDL.Func([HeroVideoConfig], [HeroVideoConfig], []),
  'setNavConfig' : IDL.Func([NavConfig], [NavConfig], []),
  'setStripeConfiguration' : IDL.Func([StripeConfiguration], [], []),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
  'updateBlogPost' : IDL.Func(
      [BlogPostId, UpdateBlogPostInput],
      [IDL.Opt(BlogPost)],
      [],
    ),
  'updateGalleryItem' : IDL.Func(
      [GalleryItemId, IDL.Text, IDL.Text, IDL.Opt(Timestamp), IDL.Text],
      [IDL.Opt(GalleryItem)],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const NavEntry = IDL.Rec();
  const _ImmutableObjectStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _ImmutableObjectStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _ImmutableObjectStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const Error = IDL.Variant({
    'FrontendOriginsNotConfigured' : IDL.Null,
    'MixedSsoSources' : IDL.Record({
      'otherKeys' : IDL.Vec(IDL.Text),
      'ssoKeys' : IDL.Vec(IDL.Text),
    }),
    'Stale' : IDL.Record({ 'ageNs' : IDL.Nat }),
    'MalformedCandid' : IDL.Null,
    'AmbiguousAttribute' : IDL.Record({
      'field' : IDL.Text,
      'sources' : IDL.Vec(IDL.Text),
    }),
    'NoAttributes' : IDL.Null,
    'UnknownNonce' : IDL.Null,
    'UntrustedSsoSource' : IDL.Record({ 'domain' : IDL.Text }),
    'MissingField' : IDL.Text,
    'FrontendOriginMismatch' : IDL.Record({
      'got' : IDL.Text,
      'expected' : IDL.Vec(IDL.Text),
    }),
  });
  const Result__1 = IDL.Variant({ 'ok' : IDL.Null, 'err' : Error });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const CreateBlogPostInput = IDL.Record({
    'title' : IDL.Text,
    'content' : IDL.Text,
    'isPublished' : IDL.Bool,
    'slug' : IDL.Text,
    'author' : IDL.Text,
    'readTime' : IDL.Text,
    'coverImage' : ExternalBlob,
    'excerpt' : IDL.Text,
    'category' : IDL.Text,
  });
  const BlogPostId = IDL.Nat;
  const Timestamp = IDL.Int;
  const BlogPost = IDL.Record({
    'id' : BlogPostId,
    'title' : IDL.Text,
    'content' : IDL.Text,
    'isPublished' : IDL.Bool,
    'createdAt' : Timestamp,
    'slug' : IDL.Text,
    'author' : IDL.Text,
    'readTime' : IDL.Text,
    'coverImage' : ExternalBlob,
    'excerpt' : IDL.Text,
    'category' : IDL.Text,
  });
  const ShoppingItem = IDL.Record({
    'productName' : IDL.Text,
    'currency' : IDL.Text,
    'quantity' : IDL.Nat,
    'priceInCents' : IDL.Nat,
    'productDescription' : IDL.Text,
  });
  const GalleryItemId = IDL.Nat;
  const GalleryItem = IDL.Record({
    'id' : GalleryItemId,
    'title' : IDL.Text,
    'createdAt' : Timestamp,
    'description' : IDL.Text,
    'category' : IDL.Text,
    'image' : ExternalBlob,
    'eventDate' : IDL.Opt(Timestamp),
  });
  const Value = IDL.Variant({
    'int' : IDL.Int,
    'nat' : IDL.Nat,
    'float' : IDL.Float64,
    'bool' : IDL.Bool,
    'null' : IDL.Null,
    'text' : IDL.Text,
  });
  const Cell = IDL.Record({ 'value' : Value, 'name' : IDL.Text });
  const Result = IDL.Record({
    'hasMore' : IDL.Bool,
    'rows' : IDL.Vec(IDL.Vec(Cell)),
  });
  const HeroVideoSlot = IDL.Record({
    'key' : IDL.Text,
    'posterUrl' : IDL.Text,
    'videoUrl' : IDL.Text,
  });
  const HeroVideoConfig = IDL.Record({ 'slots' : IDL.Vec(HeroVideoSlot) });
  NavEntry.fill(
    IDL.Record({
      'href' : IDL.Text,
      'text' : IDL.Text,
      'children' : IDL.Vec(NavEntry),
    })
  );
  const NavConfig = IDL.Record({ 'entries' : IDL.Vec(NavEntry) });
  const PostSitemapEntry = IDL.Record({
    'slug' : IDL.Text,
    'category' : IDL.Text,
    'lastmod' : Timestamp,
  });
  const StripeSessionStatus = IDL.Variant({
    'completed' : IDL.Record({
      'userPrincipal' : IDL.Opt(IDL.Text),
      'response' : IDL.Text,
    }),
    'failed' : IDL.Record({ 'error' : IDL.Text }),
  });
  const PublishedPostsPage = IDL.Record({
    'total' : IDL.Nat,
    'posts' : IDL.Vec(BlogPost),
  });
  const StripeConfiguration = IDL.Record({
    'allowedCountries' : IDL.Vec(IDL.Text),
    'secretKey' : IDL.Text,
  });
  const HttpHeader = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const HttpRequestResult = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(HttpHeader),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : HttpRequestResult,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(HttpHeader),
  });
  const UpdateBlogPostInput = IDL.Record({
    'title' : IDL.Text,
    'content' : IDL.Text,
    'isPublished' : IDL.Bool,
    'slug' : IDL.Text,
    'author' : IDL.Text,
    'readTime' : IDL.Text,
    'coverImage' : ExternalBlob,
    'excerpt' : IDL.Text,
    'category' : IDL.Text,
  });
  
  return IDL.Service({
    '_immutableObjectStorageBlobsAreLive' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [IDL.Vec(IDL.Bool)],
        ['query'],
      ),
    '_immutableObjectStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_immutableObjectStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_immutableObjectStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_ImmutableObjectStorageCreateCertificateResult],
        [],
      ),
    '_immutableObjectStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_ImmutableObjectStorageRefillInformation)],
        [_ImmutableObjectStorageRefillResult],
        [],
      ),
    '_immutableObjectStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initialize_access_control' : IDL.Func([], [], []),
    '_internet_identity_sign_in_finish' : IDL.Func([], [Result__1], []),
    '_internet_identity_sign_in_start' : IDL.Func([], [IDL.Vec(IDL.Nat8)], []),
    'addAdmin' : IDL.Func([IDL.Principal], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createBlogPost' : IDL.Func([CreateBlogPostInput], [BlogPost], []),
    'createCheckoutSession' : IDL.Func(
        [IDL.Vec(ShoppingItem), IDL.Text, IDL.Text],
        [IDL.Text],
        [],
      ),
    'createGalleryItem' : IDL.Func(
        [ExternalBlob, IDL.Text, IDL.Text, IDL.Opt(Timestamp), IDL.Text],
        [GalleryItem],
        [],
      ),
    'deleteBlogPost' : IDL.Func([BlogPostId], [IDL.Bool], []),
    'deleteGalleryItem' : IDL.Func([GalleryItemId], [IDL.Bool], []),
    'execute' : IDL.Func([IDL.Text], [Result], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getGalleryItems' : IDL.Func([], [IDL.Vec(GalleryItem)], ['query']),
    'getHeroVideoConfig' : IDL.Func([], [HeroVideoConfig], ['query']),
    'getNavConfig' : IDL.Func([], [NavConfig], ['query']),
    'getPostBySlug' : IDL.Func([IDL.Text], [IDL.Opt(BlogPost)], ['query']),
    'getPostSlugs' : IDL.Func([], [IDL.Vec(PostSitemapEntry)], ['query']),
    'getStripeSessionStatus' : IDL.Func([IDL.Text], [StripeSessionStatus], []),
    'isAdmin' : IDL.Func([IDL.Principal], [IDL.Bool], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isStripeConfigured' : IDL.Func([], [IDL.Bool], ['query']),
    'listAllPosts' : IDL.Func([], [IDL.Vec(BlogPost)], ['query']),
    'listPublishedPosts' : IDL.Func(
        [IDL.Nat, IDL.Nat],
        [PublishedPostsPage],
        ['query'],
      ),
    'listPublishedPostsByCategory' : IDL.Func(
        [IDL.Text, IDL.Nat, IDL.Nat],
        [PublishedPostsPage],
        ['query'],
      ),
    'schema' : IDL.Func([], [IDL.Text], ['query']),
    'setHeroVideoConfig' : IDL.Func([HeroVideoConfig], [HeroVideoConfig], []),
    'setNavConfig' : IDL.Func([NavConfig], [NavConfig], []),
    'setStripeConfiguration' : IDL.Func([StripeConfiguration], [], []),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
    'updateBlogPost' : IDL.Func(
        [BlogPostId, UpdateBlogPostInput],
        [IDL.Opt(BlogPost)],
        [],
      ),
    'updateGalleryItem' : IDL.Func(
        [GalleryItemId, IDL.Text, IDL.Text, IDL.Opt(Timestamp), IDL.Text],
        [IDL.Opt(GalleryItem)],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };