/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeineai/bindgen@0.2.1.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface BlogPost {
  'id' : BlogPostId,
  'title' : string,
  'content' : string,
  'isPublished' : boolean,
  'createdAt' : Timestamp,
  'slug' : string,
  'author' : string,
  'readTime' : string,
  'coverImage' : ExternalBlob,
  'excerpt' : string,
  'category' : string,
}
export type BlogPostId = bigint;
export interface Cell { 'value' : Value, 'name' : string }
export interface CreateBlogPostInput {
  'title' : string,
  'content' : string,
  'isPublished' : boolean,
  'slug' : string,
  'author' : string,
  'readTime' : string,
  'coverImage' : ExternalBlob,
  'excerpt' : string,
  'category' : string,
}
export type Error = { 'FrontendOriginsNotConfigured' : null } |
  {
    'MixedSsoSources' : {
      'otherKeys' : Array<string>,
      'ssoKeys' : Array<string>,
    }
  } |
  { 'Stale' : { 'ageNs' : bigint } } |
  { 'MalformedCandid' : null } |
  { 'AmbiguousAttribute' : { 'field' : string, 'sources' : Array<string> } } |
  { 'NoAttributes' : null } |
  { 'UnknownNonce' : null } |
  { 'UntrustedSsoSource' : { 'domain' : string } } |
  { 'MissingField' : string } |
  { 'FrontendOriginMismatch' : { 'got' : string, 'expected' : Array<string> } };
export type ExternalBlob = Uint8Array;
export interface GalleryItem {
  'id' : GalleryItemId,
  'title' : string,
  'createdAt' : Timestamp,
  'description' : string,
  'category' : string,
  'image' : ExternalBlob,
  'eventDate' : [] | [Timestamp],
}
export type GalleryItemId = bigint;
export interface HeroVideoConfig { 'slots' : Array<HeroVideoSlot> }
export interface HeroVideoSlot {
  'key' : string,
  'posterUrl' : string,
  'videoUrl' : string,
}
export interface HttpHeader { 'value' : string, 'name' : string }
export interface HttpRequestResult {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<HttpHeader>,
}
export interface NavConfig { 'entries' : Array<NavEntry> }
export interface NavEntry {
  'href' : string,
  'text' : string,
  'children' : Array<NavEntry>,
}
export interface PostSitemapEntry {
  'slug' : string,
  'category' : string,
  'lastmod' : Timestamp,
}
export interface PublishedPostsPage {
  'total' : bigint,
  'posts' : Array<BlogPost>,
}
export interface Result { 'hasMore' : boolean, 'rows' : Array<Array<Cell>> }
export type Result__1 = { 'ok' : null } |
  { 'err' : Error };
export interface ShoppingItem {
  'productName' : string,
  'currency' : string,
  'quantity' : bigint,
  'priceInCents' : bigint,
  'productDescription' : string,
}
export interface StripeConfiguration {
  'allowedCountries' : Array<string>,
  'secretKey' : string,
}
export type StripeSessionStatus = {
    'completed' : { 'userPrincipal' : [] | [string], 'response' : string }
  } |
  { 'failed' : { 'error' : string } };
export type Timestamp = bigint;
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : HttpRequestResult,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<HttpHeader>,
}
export interface UpdateBlogPostInput {
  'title' : string,
  'content' : string,
  'isPublished' : boolean,
  'slug' : string,
  'author' : string,
  'readTime' : string,
  'coverImage' : ExternalBlob,
  'excerpt' : string,
  'category' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export type Value = { 'int' : bigint } |
  { 'nat' : bigint } |
  { 'float' : number } |
  { 'bool' : boolean } |
  { 'null' : null } |
  { 'text' : string };
export interface _ImmutableObjectStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _ImmutableObjectStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _ImmutableObjectStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_immutableObjectStorageBlobsAreLive' : ActorMethod<
    [Array<Uint8Array>],
    Array<boolean>
  >,
  '_immutableObjectStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_immutableObjectStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_immutableObjectStorageCreateCertificate' : ActorMethod<
    [string],
    _ImmutableObjectStorageCreateCertificateResult
  >,
  '_immutableObjectStorageRefillCashier' : ActorMethod<
    [[] | [_ImmutableObjectStorageRefillInformation]],
    _ImmutableObjectStorageRefillResult
  >,
  '_immutableObjectStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initialize_access_control' : ActorMethod<[], undefined>,
  '_internet_identity_sign_in_finish' : ActorMethod<[], Result__1>,
  '_internet_identity_sign_in_start' : ActorMethod<[], Uint8Array>,
  'addAdmin' : ActorMethod<[Principal], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createBlogPost' : ActorMethod<[CreateBlogPostInput], BlogPost>,
  'createCheckoutSession' : ActorMethod<
    [Array<ShoppingItem>, string, string],
    string
  >,
  'createGalleryItem' : ActorMethod<
    [ExternalBlob, string, string, [] | [Timestamp], string],
    GalleryItem
  >,
  'deleteBlogPost' : ActorMethod<[BlogPostId], boolean>,
  'deleteGalleryItem' : ActorMethod<[GalleryItemId], boolean>,
  'execute' : ActorMethod<[string], Result>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getGalleryItems' : ActorMethod<[], Array<GalleryItem>>,
  'getHeroVideoConfig' : ActorMethod<[], HeroVideoConfig>,
  'getNavConfig' : ActorMethod<[], NavConfig>,
  'getPostBySlug' : ActorMethod<[string], [] | [BlogPost]>,
  'getPostSlugs' : ActorMethod<[], Array<PostSitemapEntry>>,
  'getStripeSessionStatus' : ActorMethod<[string], StripeSessionStatus>,
  'isAdmin' : ActorMethod<[Principal], boolean>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isStripeConfigured' : ActorMethod<[], boolean>,
  'listAllPosts' : ActorMethod<[], Array<BlogPost>>,
  'listPublishedPosts' : ActorMethod<[bigint, bigint], PublishedPostsPage>,
  'listPublishedPostsByCategory' : ActorMethod<
    [string, bigint, bigint],
    PublishedPostsPage
  >,
  'schema' : ActorMethod<[], string>,
  'setHeroVideoConfig' : ActorMethod<[HeroVideoConfig], HeroVideoConfig>,
  'setNavConfig' : ActorMethod<[NavConfig], NavConfig>,
  'setStripeConfiguration' : ActorMethod<[StripeConfiguration], undefined>,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
  'updateBlogPost' : ActorMethod<
    [BlogPostId, UpdateBlogPostInput],
    [] | [BlogPost]
  >,
  'updateGalleryItem' : ActorMethod<
    [GalleryItemId, string, string, [] | [Timestamp], string],
    [] | [GalleryItem]
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];