/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeineai/bindgen@0.2.1.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
import { ExternalBlob } from "@caffeineai/object-storage";
export { ExternalBlob } from "@caffeineai/object-storage";
export type Timestamp = bigint;
export interface TransformationOutput {
    status: bigint;
    body: Uint8Array;
    headers: Array<HttpHeader>;
}
export interface NavEntry {
    href: string;
    text: string;
    children: Array<NavEntry>;
}
export interface HttpRequestResult {
    status: bigint;
    body: Uint8Array;
    headers: Array<HttpHeader>;
}
export type Result__1 = {
    __kind__: "ok";
    ok: null;
} | {
    __kind__: "err";
    err: Error_;
};
export interface _ImmutableObjectStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export interface PostSitemapEntry {
    slug: string;
    category: string;
    lastmod: Timestamp;
}
export interface CreateBlogPostInput {
    title: string;
    content: string;
    isPublished: boolean;
    slug: string;
    author: string;
    readTime: string;
    coverImage: ExternalBlob;
    excerpt: string;
    category: string;
}
export interface TransformationInput {
    context: Uint8Array;
    response: HttpRequestResult;
}
export interface Cell {
    value: Value;
    name: string;
}
export type StripeSessionStatus = {
    __kind__: "completed";
    completed: {
        userPrincipal?: string;
        response: string;
    };
} | {
    __kind__: "failed";
    failed: {
        error: string;
    };
};
export interface StripeConfiguration {
    allowedCountries: Array<string>;
    secretKey: string;
}
export type Value = {
    __kind__: "int";
    int: bigint;
} | {
    __kind__: "nat";
    nat: bigint;
} | {
    __kind__: "float";
    float: number;
} | {
    __kind__: "bool";
    bool: boolean;
} | {
    __kind__: "null";
    null: null;
} | {
    __kind__: "text";
    text: string;
};
export interface HeroVideoConfig {
    slots: Array<HeroVideoSlot>;
}
export interface BlogPost {
    id: BlogPostId;
    title: string;
    content: string;
    isPublished: boolean;
    createdAt: Timestamp;
    slug: string;
    author: string;
    readTime: string;
    coverImage: ExternalBlob;
    excerpt: string;
    category: string;
}
export interface _ImmutableObjectStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface _ImmutableObjectStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface PublishedPostsPage {
    total: bigint;
    posts: Array<BlogPost>;
}
export type Error_ = {
    __kind__: "FrontendOriginsNotConfigured";
    FrontendOriginsNotConfigured: null;
} | {
    __kind__: "MixedSsoSources";
    MixedSsoSources: {
        otherKeys: Array<string>;
        ssoKeys: Array<string>;
    };
} | {
    __kind__: "Stale";
    Stale: {
        ageNs: bigint;
    };
} | {
    __kind__: "MalformedCandid";
    MalformedCandid: null;
} | {
    __kind__: "AmbiguousAttribute";
    AmbiguousAttribute: {
        field: string;
        sources: Array<string>;
    };
} | {
    __kind__: "NoAttributes";
    NoAttributes: null;
} | {
    __kind__: "UnknownNonce";
    UnknownNonce: null;
} | {
    __kind__: "UntrustedSsoSource";
    UntrustedSsoSource: {
        domain: string;
    };
} | {
    __kind__: "MissingField";
    MissingField: string;
} | {
    __kind__: "FrontendOriginMismatch";
    FrontendOriginMismatch: {
        got: string;
        expected: Array<string>;
    };
};
export interface UpdateBlogPostInput {
    title: string;
    content: string;
    isPublished: boolean;
    slug: string;
    author: string;
    readTime: string;
    coverImage: ExternalBlob;
    excerpt: string;
    category: string;
}
export interface HttpHeader {
    value: string;
    name: string;
}
export interface ShoppingItem {
    productName: string;
    currency: string;
    quantity: bigint;
    priceInCents: bigint;
    productDescription: string;
}
export interface Result {
    hasMore: boolean;
    rows: Array<Array<Cell>>;
}
export interface NavConfig {
    entries: Array<NavEntry>;
}
export type GalleryItemId = bigint;
export type BlogPostId = bigint;
export interface HeroVideoSlot {
    key: string;
    posterUrl: string;
    videoUrl: string;
}
export interface GalleryItem {
    id: GalleryItemId;
    title: string;
    createdAt: Timestamp;
    description: string;
    category: string;
    image: ExternalBlob;
    eventDate?: Timestamp;
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _immutableObjectStorageBlobsAreLive(hashes: Array<Uint8Array>): Promise<Array<boolean>>;
    _immutableObjectStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _immutableObjectStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _immutableObjectStorageCreateCertificate(blobHash: string): Promise<_ImmutableObjectStorageCreateCertificateResult>;
    _immutableObjectStorageRefillCashier(refillInformation: _ImmutableObjectStorageRefillInformation | null): Promise<_ImmutableObjectStorageRefillResult>;
    _immutableObjectStorageUpdateGatewayPrincipals(): Promise<void>;
    _initialize_access_control(): Promise<void>;
    _internet_identity_sign_in_finish(): Promise<Result__1>;
    _internet_identity_sign_in_start(): Promise<Uint8Array>;
    addAdmin(principal: Principal): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    createBlogPost(input: CreateBlogPostInput): Promise<BlogPost>;
    createCheckoutSession(items: Array<ShoppingItem>, successUrl: string, cancelUrl: string): Promise<string>;
    createGalleryItem(image: ExternalBlob, title: string, description: string, eventDate: Timestamp | null, category: string): Promise<GalleryItem>;
    deleteBlogPost(id: BlogPostId): Promise<boolean>;
    deleteGalleryItem(id: GalleryItemId): Promise<boolean>;
    execute(qJson: string): Promise<Result>;
    getCallerUserRole(): Promise<UserRole>;
    getGalleryItems(): Promise<Array<GalleryItem>>;
    getHeroVideoConfig(): Promise<HeroVideoConfig>;
    getNavConfig(): Promise<NavConfig>;
    getPostBySlug(slug: string): Promise<BlogPost | null>;
    getPostSlugs(): Promise<Array<PostSitemapEntry>>;
    getStripeSessionStatus(sessionId: string): Promise<StripeSessionStatus>;
    isAdmin(caller: Principal): Promise<boolean>;
    isCallerAdmin(): Promise<boolean>;
    isStripeConfigured(): Promise<boolean>;
    listAllPosts(): Promise<Array<BlogPost>>;
    listPublishedPosts(offset: bigint, limit: bigint): Promise<PublishedPostsPage>;
    listPublishedPostsByCategory(category: string, offset: bigint, limit: bigint): Promise<PublishedPostsPage>;
    schema(): Promise<string>;
    setHeroVideoConfig(config: HeroVideoConfig): Promise<HeroVideoConfig>;
    setNavConfig(config: NavConfig): Promise<NavConfig>;
    setStripeConfiguration(config: StripeConfiguration): Promise<void>;
    transform(input: TransformationInput): Promise<TransformationOutput>;
    updateBlogPost(id: BlogPostId, input: UpdateBlogPostInput): Promise<BlogPost | null>;
    updateGalleryItem(id: GalleryItemId, title: string, description: string, eventDate: Timestamp | null, category: string): Promise<GalleryItem | null>;
}
import type { BlogPost as _BlogPost, BlogPostId as _BlogPostId, Cell as _Cell, CreateBlogPostInput as _CreateBlogPostInput, Error as _Error, ExternalBlob as _ExternalBlob, GalleryItem as _GalleryItem, GalleryItemId as _GalleryItemId, NavConfig as _NavConfig, NavEntry as _NavEntry, PublishedPostsPage as _PublishedPostsPage, Result as _Result, Result__1 as _Result__1, StripeSessionStatus as _StripeSessionStatus, Timestamp as _Timestamp, UpdateBlogPostInput as _UpdateBlogPostInput, UserRole as _UserRole, Value as _Value, _ImmutableObjectStorageRefillInformation as __ImmutableObjectStorageRefillInformation, _ImmutableObjectStorageRefillResult as __ImmutableObjectStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _immutableObjectStorageBlobsAreLive(arg0: Array<Uint8Array>): Promise<Array<boolean>> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageBlobsAreLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageBlobsAreLive(arg0);
            return result;
        }
    }
    async _immutableObjectStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageBlobsToDelete();
            return result;
        }
    }
    async _immutableObjectStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _immutableObjectStorageCreateCertificate(arg0: string): Promise<_ImmutableObjectStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _immutableObjectStorageRefillCashier(arg0: _ImmutableObjectStorageRefillInformation | null): Promise<_ImmutableObjectStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__ImmutableObjectStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__ImmutableObjectStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _immutableObjectStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async _initialize_access_control(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initialize_access_control();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initialize_access_control();
            return result;
        }
    }
    async _internet_identity_sign_in_finish(): Promise<Result__1> {
        if (this.processError) {
            try {
                const result = await this.actor._internet_identity_sign_in_finish();
                return from_candid_Result__1_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._internet_identity_sign_in_finish();
            return from_candid_Result__1_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async _internet_identity_sign_in_start(): Promise<Uint8Array> {
        if (this.processError) {
            try {
                const result = await this.actor._internet_identity_sign_in_start();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._internet_identity_sign_in_start();
            return result;
        }
    }
    async addAdmin(arg0: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addAdmin(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addAdmin(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n12(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n12(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createBlogPost(arg0: CreateBlogPostInput): Promise<BlogPost> {
        if (this.processError) {
            try {
                const result = await this.actor.createBlogPost(await to_candid_CreateBlogPostInput_n14(this._uploadFile, this._downloadFile, arg0));
                return from_candid_BlogPost_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createBlogPost(await to_candid_CreateBlogPostInput_n14(this._uploadFile, this._downloadFile, arg0));
            return from_candid_BlogPost_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async createCheckoutSession(arg0: Array<ShoppingItem>, arg1: string, arg2: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.createCheckoutSession(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createCheckoutSession(arg0, arg1, arg2);
            return result;
        }
    }
    async createGalleryItem(arg0: ExternalBlob, arg1: string, arg2: string, arg3: Timestamp | null, arg4: string): Promise<GalleryItem> {
        if (this.processError) {
            try {
                const result = await this.actor.createGalleryItem(await to_candid_ExternalBlob_n16(this._uploadFile, this._downloadFile, arg0), arg1, arg2, to_candid_opt_n20(this._uploadFile, this._downloadFile, arg3), arg4);
                return from_candid_GalleryItem_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createGalleryItem(await to_candid_ExternalBlob_n16(this._uploadFile, this._downloadFile, arg0), arg1, arg2, to_candid_opt_n20(this._uploadFile, this._downloadFile, arg3), arg4);
            return from_candid_GalleryItem_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async deleteBlogPost(arg0: BlogPostId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteBlogPost(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteBlogPost(arg0);
            return result;
        }
    }
    async deleteGalleryItem(arg0: GalleryItemId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteGalleryItem(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteGalleryItem(arg0);
            return result;
        }
    }
    async execute(arg0: string): Promise<Result> {
        if (this.processError) {
            try {
                const result = await this.actor.execute(arg0);
                return from_candid_Result_n24(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.execute(arg0);
            return from_candid_Result_n24(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n32(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n32(this._uploadFile, this._downloadFile, result);
        }
    }
    async getGalleryItems(): Promise<Array<GalleryItem>> {
        if (this.processError) {
            try {
                const result = await this.actor.getGalleryItems();
                return from_candid_vec_n34(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getGalleryItems();
            return from_candid_vec_n34(this._uploadFile, this._downloadFile, result);
        }
    }
    async getHeroVideoConfig(): Promise<HeroVideoConfig> {
        if (this.processError) {
            try {
                const result = await this.actor.getHeroVideoConfig();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getHeroVideoConfig();
            return result;
        }
    }
    async getNavConfig(): Promise<NavConfig> {
        if (this.processError) {
            try {
                const result = await this.actor.getNavConfig();
                return from_candid_NavConfig_n35(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getNavConfig();
            return from_candid_NavConfig_n35(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPostBySlug(arg0: string): Promise<BlogPost | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getPostBySlug(arg0);
                return from_candid_opt_n40(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPostBySlug(arg0);
            return from_candid_opt_n40(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPostSlugs(): Promise<Array<PostSitemapEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPostSlugs();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPostSlugs();
            return result;
        }
    }
    async getStripeSessionStatus(arg0: string): Promise<StripeSessionStatus> {
        if (this.processError) {
            try {
                const result = await this.actor.getStripeSessionStatus(arg0);
                return from_candid_StripeSessionStatus_n41(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStripeSessionStatus(arg0);
            return from_candid_StripeSessionStatus_n41(this._uploadFile, this._downloadFile, result);
        }
    }
    async isAdmin(arg0: Principal): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isAdmin(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isAdmin(arg0);
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async isStripeConfigured(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isStripeConfigured();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isStripeConfigured();
            return result;
        }
    }
    async listAllPosts(): Promise<Array<BlogPost>> {
        if (this.processError) {
            try {
                const result = await this.actor.listAllPosts();
                return from_candid_vec_n45(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listAllPosts();
            return from_candid_vec_n45(this._uploadFile, this._downloadFile, result);
        }
    }
    async listPublishedPosts(arg0: bigint, arg1: bigint): Promise<PublishedPostsPage> {
        if (this.processError) {
            try {
                const result = await this.actor.listPublishedPosts(arg0, arg1);
                return from_candid_PublishedPostsPage_n46(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listPublishedPosts(arg0, arg1);
            return from_candid_PublishedPostsPage_n46(this._uploadFile, this._downloadFile, result);
        }
    }
    async listPublishedPostsByCategory(arg0: string, arg1: bigint, arg2: bigint): Promise<PublishedPostsPage> {
        if (this.processError) {
            try {
                const result = await this.actor.listPublishedPostsByCategory(arg0, arg1, arg2);
                return from_candid_PublishedPostsPage_n46(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listPublishedPostsByCategory(arg0, arg1, arg2);
            return from_candid_PublishedPostsPage_n46(this._uploadFile, this._downloadFile, result);
        }
    }
    async schema(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.schema();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.schema();
            return result;
        }
    }
    async setHeroVideoConfig(arg0: HeroVideoConfig): Promise<HeroVideoConfig> {
        if (this.processError) {
            try {
                const result = await this.actor.setHeroVideoConfig(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setHeroVideoConfig(arg0);
            return result;
        }
    }
    async setNavConfig(arg0: NavConfig): Promise<NavConfig> {
        if (this.processError) {
            try {
                const result = await this.actor.setNavConfig(to_candid_NavConfig_n48(this._uploadFile, this._downloadFile, arg0));
                return from_candid_NavConfig_n35(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setNavConfig(to_candid_NavConfig_n48(this._uploadFile, this._downloadFile, arg0));
            return from_candid_NavConfig_n35(this._uploadFile, this._downloadFile, result);
        }
    }
    async setStripeConfiguration(arg0: StripeConfiguration): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setStripeConfiguration(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setStripeConfiguration(arg0);
            return result;
        }
    }
    async transform(arg0: TransformationInput): Promise<TransformationOutput> {
        if (this.processError) {
            try {
                const result = await this.actor.transform(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.transform(arg0);
            return result;
        }
    }
    async updateBlogPost(arg0: BlogPostId, arg1: UpdateBlogPostInput): Promise<BlogPost | null> {
        if (this.processError) {
            try {
                const result = await this.actor.updateBlogPost(arg0, await to_candid_UpdateBlogPostInput_n53(this._uploadFile, this._downloadFile, arg1));
                return from_candid_opt_n40(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateBlogPost(arg0, await to_candid_UpdateBlogPostInput_n53(this._uploadFile, this._downloadFile, arg1));
            return from_candid_opt_n40(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateGalleryItem(arg0: GalleryItemId, arg1: string, arg2: string, arg3: Timestamp | null, arg4: string): Promise<GalleryItem | null> {
        if (this.processError) {
            try {
                const result = await this.actor.updateGalleryItem(arg0, arg1, arg2, to_candid_opt_n20(this._uploadFile, this._downloadFile, arg3), arg4);
                return from_candid_opt_n54(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateGalleryItem(arg0, arg1, arg2, to_candid_opt_n20(this._uploadFile, this._downloadFile, arg3), arg4);
            return from_candid_opt_n54(this._uploadFile, this._downloadFile, result);
        }
    }
}
async function from_candid_BlogPost_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _BlogPost): Promise<BlogPost> {
    return await from_candid_record_n18(_uploadFile, _downloadFile, value);
}
function from_candid_Cell_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Cell): Cell {
    return from_candid_record_n29(_uploadFile, _downloadFile, value);
}
function from_candid_Error_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Error): Error_ {
    return from_candid_variant_n11(_uploadFile, _downloadFile, value);
}
async function from_candid_ExternalBlob_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExternalBlob): Promise<ExternalBlob> {
    return await _downloadFile(value);
}
async function from_candid_GalleryItem_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _GalleryItem): Promise<GalleryItem> {
    return await from_candid_record_n22(_uploadFile, _downloadFile, value);
}
function from_candid_NavConfig_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _NavConfig): NavConfig {
    return from_candid_record_n36(_uploadFile, _downloadFile, value);
}
function from_candid_NavEntry_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _NavEntry): NavEntry {
    return from_candid_record_n39(_uploadFile, _downloadFile, value);
}
async function from_candid_PublishedPostsPage_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PublishedPostsPage): Promise<PublishedPostsPage> {
    return await from_candid_record_n47(_uploadFile, _downloadFile, value);
}
function from_candid_Result__1_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result__1): Result__1 {
    return from_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function from_candid_Result_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result): Result {
    return from_candid_record_n25(_uploadFile, _downloadFile, value);
}
function from_candid_StripeSessionStatus_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _StripeSessionStatus): StripeSessionStatus {
    return from_candid_variant_n42(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n33(_uploadFile, _downloadFile, value);
}
function from_candid_Value_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Value): Value {
    return from_candid_variant_n31(_uploadFile, _downloadFile, value);
}
function from_candid__ImmutableObjectStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __ImmutableObjectStorageRefillResult): _ImmutableObjectStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Timestamp]): Timestamp | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_opt_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_BlogPost]): Promise<BlogPost | null> {
    return value.length === 0 ? null : await from_candid_BlogPost_n17(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_opt_n54(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_GalleryItem]): Promise<GalleryItem | null> {
    return value.length === 0 ? null : await from_candid_GalleryItem_n21(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_record_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _BlogPostId;
    title: string;
    content: string;
    isPublished: boolean;
    createdAt: _Timestamp;
    slug: string;
    author: string;
    readTime: string;
    coverImage: _ExternalBlob;
    excerpt: string;
    category: string;
}): Promise<{
    id: BlogPostId;
    title: string;
    content: string;
    isPublished: boolean;
    createdAt: Timestamp;
    slug: string;
    author: string;
    readTime: string;
    coverImage: ExternalBlob;
    excerpt: string;
    category: string;
}> {
    return {
        id: value.id,
        title: value.title,
        content: value.content,
        isPublished: value.isPublished,
        createdAt: value.createdAt,
        slug: value.slug,
        author: value.author,
        readTime: value.readTime,
        coverImage: await from_candid_ExternalBlob_n19(_uploadFile, _downloadFile, value.coverImage),
        excerpt: value.excerpt,
        category: value.category
    };
}
async function from_candid_record_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _GalleryItemId;
    title: string;
    createdAt: _Timestamp;
    description: string;
    category: string;
    image: _ExternalBlob;
    eventDate: [] | [_Timestamp];
}): Promise<{
    id: GalleryItemId;
    title: string;
    createdAt: Timestamp;
    description: string;
    category: string;
    image: ExternalBlob;
    eventDate?: Timestamp;
}> {
    return {
        id: value.id,
        title: value.title,
        createdAt: value.createdAt,
        description: value.description,
        category: value.category,
        image: await from_candid_ExternalBlob_n19(_uploadFile, _downloadFile, value.image),
        eventDate: record_opt_to_undefined(from_candid_opt_n23(_uploadFile, _downloadFile, value.eventDate))
    };
}
function from_candid_record_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    hasMore: boolean;
    rows: Array<Array<_Cell>>;
}): {
    hasMore: boolean;
    rows: Array<Array<Cell>>;
} {
    return {
        hasMore: value.hasMore,
        rows: from_candid_vec_n26(_uploadFile, _downloadFile, value.rows)
    };
}
function from_candid_record_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    value: _Value;
    name: string;
}): {
    value: Value;
    name: string;
} {
    return {
        value: from_candid_Value_n30(_uploadFile, _downloadFile, value.value),
        name: value.name
    };
}
function from_candid_record_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    entries: Array<_NavEntry>;
}): {
    entries: Array<NavEntry>;
} {
    return {
        entries: from_candid_vec_n37(_uploadFile, _downloadFile, value.entries)
    };
}
function from_candid_record_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    href: string;
    text: string;
    children: Array<_NavEntry>;
}): {
    href: string;
    text: string;
    children: Array<NavEntry>;
} {
    return {
        href: value.href,
        text: value.text,
        children: from_candid_vec_n37(_uploadFile, _downloadFile, value.children)
    };
}
function from_candid_record_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    userPrincipal: [] | [string];
    response: string;
}): {
    userPrincipal?: string;
    response: string;
} {
    return {
        userPrincipal: record_opt_to_undefined(from_candid_opt_n44(_uploadFile, _downloadFile, value.userPrincipal)),
        response: value.response
    };
}
async function from_candid_record_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    total: bigint;
    posts: Array<_BlogPost>;
}): Promise<{
    total: bigint;
    posts: Array<BlogPost>;
}> {
    return {
        total: value.total,
        posts: await from_candid_vec_n45(_uploadFile, _downloadFile, value.posts)
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_variant_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    FrontendOriginsNotConfigured: null;
} | {
    MixedSsoSources: {
        otherKeys: Array<string>;
        ssoKeys: Array<string>;
    };
} | {
    Stale: {
        ageNs: bigint;
    };
} | {
    MalformedCandid: null;
} | {
    AmbiguousAttribute: {
        field: string;
        sources: Array<string>;
    };
} | {
    NoAttributes: null;
} | {
    UnknownNonce: null;
} | {
    UntrustedSsoSource: {
        domain: string;
    };
} | {
    MissingField: string;
} | {
    FrontendOriginMismatch: {
        got: string;
        expected: Array<string>;
    };
}): {
    __kind__: "FrontendOriginsNotConfigured";
    FrontendOriginsNotConfigured: null;
} | {
    __kind__: "MixedSsoSources";
    MixedSsoSources: {
        otherKeys: Array<string>;
        ssoKeys: Array<string>;
    };
} | {
    __kind__: "Stale";
    Stale: {
        ageNs: bigint;
    };
} | {
    __kind__: "MalformedCandid";
    MalformedCandid: null;
} | {
    __kind__: "AmbiguousAttribute";
    AmbiguousAttribute: {
        field: string;
        sources: Array<string>;
    };
} | {
    __kind__: "NoAttributes";
    NoAttributes: null;
} | {
    __kind__: "UnknownNonce";
    UnknownNonce: null;
} | {
    __kind__: "UntrustedSsoSource";
    UntrustedSsoSource: {
        domain: string;
    };
} | {
    __kind__: "MissingField";
    MissingField: string;
} | {
    __kind__: "FrontendOriginMismatch";
    FrontendOriginMismatch: {
        got: string;
        expected: Array<string>;
    };
} {
    return "FrontendOriginsNotConfigured" in value ? {
        __kind__: "FrontendOriginsNotConfigured",
        FrontendOriginsNotConfigured: value.FrontendOriginsNotConfigured
    } : "MixedSsoSources" in value ? {
        __kind__: "MixedSsoSources",
        MixedSsoSources: value.MixedSsoSources
    } : "Stale" in value ? {
        __kind__: "Stale",
        Stale: value.Stale
    } : "MalformedCandid" in value ? {
        __kind__: "MalformedCandid",
        MalformedCandid: value.MalformedCandid
    } : "AmbiguousAttribute" in value ? {
        __kind__: "AmbiguousAttribute",
        AmbiguousAttribute: value.AmbiguousAttribute
    } : "NoAttributes" in value ? {
        __kind__: "NoAttributes",
        NoAttributes: value.NoAttributes
    } : "UnknownNonce" in value ? {
        __kind__: "UnknownNonce",
        UnknownNonce: value.UnknownNonce
    } : "UntrustedSsoSource" in value ? {
        __kind__: "UntrustedSsoSource",
        UntrustedSsoSource: value.UntrustedSsoSource
    } : "MissingField" in value ? {
        __kind__: "MissingField",
        MissingField: value.MissingField
    } : "FrontendOriginMismatch" in value ? {
        __kind__: "FrontendOriginMismatch",
        FrontendOriginMismatch: value.FrontendOriginMismatch
    } : value;
}
function from_candid_variant_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    int: bigint;
} | {
    nat: bigint;
} | {
    float: number;
} | {
    bool: boolean;
} | {
    null: null;
} | {
    text: string;
}): {
    __kind__: "int";
    int: bigint;
} | {
    __kind__: "nat";
    nat: bigint;
} | {
    __kind__: "float";
    float: number;
} | {
    __kind__: "bool";
    bool: boolean;
} | {
    __kind__: "null";
    null: null;
} | {
    __kind__: "text";
    text: string;
} {
    return "int" in value ? {
        __kind__: "int",
        int: value.int
    } : "nat" in value ? {
        __kind__: "nat",
        nat: value.nat
    } : "float" in value ? {
        __kind__: "float",
        float: value.float
    } : "bool" in value ? {
        __kind__: "bool",
        bool: value.bool
    } : "null" in value ? {
        __kind__: "null",
        null: value.null
    } : "text" in value ? {
        __kind__: "text",
        text: value.text
    } : value;
}
function from_candid_variant_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    completed: {
        userPrincipal: [] | [string];
        response: string;
    };
} | {
    failed: {
        error: string;
    };
}): {
    __kind__: "completed";
    completed: {
        userPrincipal?: string;
        response: string;
    };
} | {
    __kind__: "failed";
    failed: {
        error: string;
    };
} {
    return "completed" in value ? {
        __kind__: "completed",
        completed: from_candid_record_n43(_uploadFile, _downloadFile, value.completed)
    } : "failed" in value ? {
        __kind__: "failed",
        failed: value.failed
    } : value;
}
function from_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: null;
} | {
    err: _Error;
}): {
    __kind__: "ok";
    ok: null;
} | {
    __kind__: "err";
    err: Error_;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: from_candid_Error_n10(_uploadFile, _downloadFile, value.err)
    } : value;
}
function from_candid_vec_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<Array<_Cell>>): Array<Array<Cell>> {
    return value.map((x)=>from_candid_vec_n27(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Cell>): Array<Cell> {
    return value.map((x)=>from_candid_Cell_n28(_uploadFile, _downloadFile, x));
}
async function from_candid_vec_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_GalleryItem>): Promise<Array<GalleryItem>> {
    return await Promise.all(value.map(async (x)=>await from_candid_GalleryItem_n21(_uploadFile, _downloadFile, x)));
}
function from_candid_vec_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_NavEntry>): Array<NavEntry> {
    return value.map((x)=>from_candid_NavEntry_n38(_uploadFile, _downloadFile, x));
}
async function from_candid_vec_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_BlogPost>): Promise<Array<BlogPost>> {
    return await Promise.all(value.map(async (x)=>await from_candid_BlogPost_n17(_uploadFile, _downloadFile, x)));
}
async function to_candid_CreateBlogPostInput_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CreateBlogPostInput): Promise<_CreateBlogPostInput> {
    return await to_candid_record_n15(_uploadFile, _downloadFile, value);
}
async function to_candid_ExternalBlob_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExternalBlob): Promise<_ExternalBlob> {
    return await _uploadFile(value);
}
function to_candid_NavConfig_n48(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: NavConfig): _NavConfig {
    return to_candid_record_n49(_uploadFile, _downloadFile, value);
}
function to_candid_NavEntry_n51(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: NavEntry): _NavEntry {
    return to_candid_record_n52(_uploadFile, _downloadFile, value);
}
async function to_candid_UpdateBlogPostInput_n53(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UpdateBlogPostInput): Promise<_UpdateBlogPostInput> {
    return await to_candid_record_n15(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n13(_uploadFile, _downloadFile, value);
}
function to_candid__ImmutableObjectStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ImmutableObjectStorageRefillInformation): __ImmutableObjectStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ImmutableObjectStorageRefillInformation | null): [] | [__ImmutableObjectStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__ImmutableObjectStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
function to_candid_opt_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Timestamp | null): [] | [_Timestamp] {
    return value === null ? candid_none() : candid_some(value);
}
async function to_candid_record_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    title: string;
    content: string;
    isPublished: boolean;
    slug: string;
    author: string;
    readTime: string;
    coverImage: ExternalBlob;
    excerpt: string;
    category: string;
}): Promise<{
    title: string;
    content: string;
    isPublished: boolean;
    slug: string;
    author: string;
    readTime: string;
    coverImage: _ExternalBlob;
    excerpt: string;
    category: string;
}> {
    return {
        title: value.title,
        content: value.content,
        isPublished: value.isPublished,
        slug: value.slug,
        author: value.author,
        readTime: value.readTime,
        coverImage: await to_candid_ExternalBlob_n16(_uploadFile, _downloadFile, value.coverImage),
        excerpt: value.excerpt,
        category: value.category
    };
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
function to_candid_record_n49(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    entries: Array<NavEntry>;
}): {
    entries: Array<_NavEntry>;
} {
    return {
        entries: to_candid_vec_n50(_uploadFile, _downloadFile, value.entries)
    };
}
function to_candid_record_n52(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    href: string;
    text: string;
    children: Array<NavEntry>;
}): {
    href: string;
    text: string;
    children: Array<_NavEntry>;
} {
    return {
        href: value.href,
        text: value.text,
        children: to_candid_vec_n50(_uploadFile, _downloadFile, value.children)
    };
}
function to_candid_variant_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_vec_n50(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<NavEntry>): Array<_NavEntry> {
    return value.map((x)=>to_candid_NavEntry_n51(_uploadFile, _downloadFile, x));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
